version: 0.2


phases:
  install :
    commands:
        - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
        - sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
        - wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list 
        - sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
        - sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
        - sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install aspnetcore-runtime-2.1
        - sudo apt-get install dotnet-sdk-2.1

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=715024434565.dkr.ecr.us-east-1.amazonaws.com/net-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
    files: imagedefinitions.json
