version: 0.2
# Declaration of environment variables
environment_variables:
 plaintext:
  REPOSITORY_URI: "715024434565.dkr.ecr.us-east-1.amazonaws.com/net-app"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - Install-Package -Name AWSPowerShell -Force
      - Install-Module DockerMsftProvider -Force
      - Install-Package Docker -ProviderName DockerMsftProvider -Force
      - Invoke-Expression -Command (Get-ECRLoginCommand -Region us-east-1).Command
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
    files: imagedefinitions.json
